FROM ubuntu:latest
FROM python:3.7-slim
WORKDIR /code
ADD /data /code
COPY requirements.txt requirements.txt
RUN apt-get update
RUN apt-get install libglib2.0-0 -y
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN pip install -r requirements.txt

#RUN apk add opencv-python
#CMD["sudo", "apt","install","opencv-python"]
CMD ["python", "/code/test.py"]
